on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.0
        with:
          nsis-version: 3.08
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - name: Setup Python App
        run: |
          pip install -r requirements.txt 
          pyinstaller SoundSwitch.spec
          pyinstaller SoundSampleRecorder.spec
          copy dist\SoundSampleRecorder\SoundSampleRecorder.exe dist\SoundSwitch\
      - name: Make NSIS
        run: |
          & "C:\Program Files (x86)\NSIS\makensis.exe" "SoundSwitch.nsi"
      - name: Upload exe
        uses: actions/upload-artifact@v3
        with:
          name: Windows Release
          path: SoundSwitchInstaller.exe
